# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/alan/Learning/FPGA/fpgachina/Audio_migrate/vivado/constraints/base.xdc

# Block Designs: bd/audio/audio.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio || ORIG_REF_NAME==audio} -quiet] -quiet

# IP: bd/audio/ip/audio_processing_system7_0_0/audio_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_processing_system7_0_0 || ORIG_REF_NAME==audio_processing_system7_0_0} -quiet] -quiet

# IP: bd/audio/ip/audio_axi_interconnect_0_0/audio_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_axi_interconnect_0_0 || ORIG_REF_NAME==audio_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/audio/ip/audio_clk_wiz_0_0/audio_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_clk_wiz_0_0 || ORIG_REF_NAME==audio_clk_wiz_0_0} -quiet] -quiet

# IP: bd/audio/ip/audio_proc_sys_reset_0_0/audio_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_proc_sys_reset_0_0 || ORIG_REF_NAME==audio_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/audio/ip/audio_audio_codec_ctrl_0_0/audio_audio_codec_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_audio_codec_ctrl_0_0 || ORIG_REF_NAME==audio_audio_codec_ctrl_0_0} -quiet] -quiet

# IP: bd/audio/ip/audio_axi_gpio_0_0/audio_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_axi_gpio_0_0 || ORIG_REF_NAME==audio_axi_gpio_0_0} -quiet] -quiet

# IP: bd/audio/ip/audio_axi_gpio_0_1/audio_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_axi_gpio_0_1 || ORIG_REF_NAME==audio_axi_gpio_0_1} -quiet] -quiet

# IP: bd/audio/ip/audio_axi_gpio_0_2/audio_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_axi_gpio_0_2 || ORIG_REF_NAME==audio_axi_gpio_0_2} -quiet] -quiet

# IP: bd/audio/ip/audio_axi_gpio_0_3/audio_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_axi_gpio_0_3 || ORIG_REF_NAME==audio_axi_gpio_0_3} -quiet] -quiet

# IP: bd/audio/ip/audio_axi_interconnect_0_upgraded_ipi_imp_xbar_0/audio_axi_interconnect_0_upgraded_ipi_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_axi_interconnect_0_upgraded_ipi_imp_xbar_0 || ORIG_REF_NAME==audio_axi_interconnect_0_upgraded_ipi_imp_xbar_0} -quiet] -quiet

# IP: bd/audio/ip/audio_axi_interconnect_0_imp_s00_regslice_0/audio_axi_interconnect_0_imp_s00_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_axi_interconnect_0_imp_s00_regslice_0 || ORIG_REF_NAME==audio_axi_interconnect_0_imp_s00_regslice_0} -quiet] -quiet

# IP: bd/audio/ip/audio_axi_interconnect_0_imp_auto_pc_0/audio_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==audio_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# XDC: /home/alan/Learning/FPGA/fpgachina/Audio_migrate/audio_test/audio_test.gen/sources_1/bd/audio/audio_ooc.xdc
