# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alan/Learning/FPGA/fpgachina/Audio_migrate/audio_test/audio_test.srcs/sources_1/bd/audio/ip/audio_proc_sys_reset_0_0/audio_proc_sys_reset_0_0.xci
# IP: The module: 'audio_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alan/Learning/FPGA/fpgachina/Audio_migrate/audio_test/audio_test.gen/sources_1/bd/audio/ip/audio_proc_sys_reset_0_0/audio_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/alan/Learning/FPGA/fpgachina/Audio_migrate/audio_test/audio_test.gen/sources_1/bd/audio/ip/audio_proc_sys_reset_0_0/audio_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/alan/Learning/FPGA/fpgachina/Audio_migrate/audio_test/audio_test.gen/sources_1/bd/audio/ip/audio_proc_sys_reset_0_0/audio_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/alan/Learning/FPGA/fpgachina/Audio_migrate/audio_test/audio_test.srcs/sources_1/bd/audio/ip/audio_proc_sys_reset_0_0/audio_proc_sys_reset_0_0.xci
# IP: The module: 'audio_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alan/Learning/FPGA/fpgachina/Audio_migrate/audio_test/audio_test.gen/sources_1/bd/audio/ip/audio_proc_sys_reset_0_0/audio_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/alan/Learning/FPGA/fpgachina/Audio_migrate/audio_test/audio_test.gen/sources_1/bd/audio/ip/audio_proc_sys_reset_0_0/audio_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/alan/Learning/FPGA/fpgachina/Audio_migrate/audio_test/audio_test.gen/sources_1/bd/audio/ip/audio_proc_sys_reset_0_0/audio_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
