# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alan/Learning/FPGA/fpgachina/Audio_migrate/audio_test/audio_test.srcs/sources_1/bd/audio/ip/audio_axi_interconnect_0_imp_auto_pc_0/audio_axi_interconnect_0_imp_auto_pc_0.xci
# IP: The module: 'audio_axi_interconnect_0_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alan/Learning/FPGA/fpgachina/Audio_migrate/audio_test/audio_test.gen/sources_1/bd/audio/ip/audio_axi_interconnect_0_imp_auto_pc_0/audio_axi_interconnect_0_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_axi_interconnect_0_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/alan/Learning/FPGA/fpgachina/Audio_migrate/audio_test/audio_test.srcs/sources_1/bd/audio/ip/audio_axi_interconnect_0_imp_auto_pc_0/audio_axi_interconnect_0_imp_auto_pc_0.xci
# IP: The module: 'audio_axi_interconnect_0_imp_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alan/Learning/FPGA/fpgachina/Audio_migrate/audio_test/audio_test.gen/sources_1/bd/audio/ip/audio_axi_interconnect_0_imp_auto_pc_0/audio_axi_interconnect_0_imp_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_axi_interconnect_0_imp_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
